### ISSUE TITLE
improperly placed imports

### ISSUE THREAD

**Issue by whoisearth** [maksim77/zsender#1]
You have numerous places within your classes where you are doing `import xxxx`

Please put all imports at the beginning of the file like this - 

```
import json
import re
import socket
import time


class ZabbixSender:
....
```

This saves burying import statements inside of code that could grow with time and also avoids calling an import more than once (you currently are importing json in 3 separate places.

**Comment by maksim77** [comment]
Thank you!
Of course you are right.

**Comment by whoisearth** [comment]
My pleasure :)  btw. I love this little snippet of code.  I wasn't happy running the commandline zabbix_sender.  At least this way I'm going direct to the API.
