### ISSUE TITLE
Error when install from pip

### ISSUE THREAD

**Issue by DANic-git** [maksim77/zsender#4]
pip install ZabbixSender
Collecting ZabbixSender
  Downloading ZabbixSender-0.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fu369d/ZabbixSender/setup.py", line 6, in <module>
        long_description=open('README.rst', 'r').read() + '\n\n' + open(
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fu                                                                                                                                       369d/ZabbixSender/

**Comment by maksim77** [comment]
Sorry I forgot to reply here. Thank you for the comment problem is fixed. I want to draw your attention to the fact that the development of module DISCONTINUED. I recommend to use [py-zabbix](https://github.com/blacked/py-zabbix).
