### ISSUE TITLE
TypeError: ZabbixSender() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by fengbao207** [maksim77/zsender#5]
I had a issue,please help, thanks.
And  Why i use  the  ZabbixSender  sending  data to zabbix , must wait  creatting  item after 30s later,

**Comment by maksim77** [comment]
Please note the section "Disclaimer" in the readme file.

> Development of this module stopped! All ideas and solutions will be transferred into py-zabbix. py-zabbix is much more powerful project, and I don't want to reinvent the wheel.

**Comment by fengbao207** [comment]
ok,thanks. i will try to use py-zabbix.
