### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by DeMaH4uK** [maksim77/zsender#9]
Доброго времени суток.
В строке 36 файла ZabbixSender.py (status = re_status.search(status).groups()[0]) возникает ошибка AttributeError: 'NoneType' object has no attribute 'groups'.
С чем это связано?

**Comment by rafaelsupport** [comment]
@DeMaH4uK did you fix this?

**Comment by maksim77** [comment]
> @DeMaH4uK did you fix this?

Development this module was stopped 8 years ago! I think you should search some alternative...
